FROM python:3.5

RUN apt-get update && apt-get install -y python3.4 vim 

WORKDIR /usr/src
RUN apt-get install -y mercurial
#RUN hg clone https://sbellem@bitbucket.org/birkenfeld/sphinx-contrib
RUN hg clone https://sbellem@bitbucket.org/sbellem/sphinx-contrib
WORKDIR /usr/src/sphinx-contrib/examplecode
RUN python setup.py install

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN pip install --upgrade pip

COPY . /usr/src/app/

RUN pip install --no-cache-dir -e .[dev]
RUN bigchaindb -y configure
